### ISSUE TITLE
Issue with pytiled on WSL

### ISSUE THREAD

**Issue by wolfj95** [the-isf-academy/quest#13]
After solving issue documented here:

_Originally posted by @wolfj95 in https://github.com/the-isf-academy/quest/issues/6#issuecomment-603108837_

There is still an error when trying to run an example game from the Quest examples as a module on WSL (ie `python3 -m quest.examples.island`)

**Comment by wolfj95** [comment]
error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/jwolf/Desktop/cs9/unit_02/quest_lab/quest/examples/island.py", line 1, in <module>
    from quest.game import QuestGame
  File "/mnt/c/Users/jwolf/Desktop/cs9/unit_02/quest_lab/quest/game.py", line 1, in <module>
    import arcade
  File "/usr/local/lib/python3.6/dist-packages/arcade/__init__.py", line 226, in <module>
    from .tilemap import get_tilemap_layer
  File "/usr/local/lib/python3.6/dist-packages/arcade/tilemap.py", line 17, in <module>
    import pytiled_parser
  File "/usr/local/lib/python3.6/dist-packages/pytiled_parser/__init__.py", line 3, in <module>
    from . import objects, utilities
  File "/usr/local/lib/python3.6/dist-packages/pytiled_parser/objects.py", line 178, in <module>
    @attr.s(auto_attribs=True, kw_only=True)
TypeError: attrs() got an unexpected keyword argument 'kw_only'
```
