### ISSUE TITLE
Problems using pyglet with Windows machines running Ubuntu

### ISSUE THREAD

**Issue by wolfj95** [the-isf-academy/quest#6]
Error from run:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/bryan/desktop/cs9/unit2/quest_lab/quest/examples/island.py", line 1, in <module>
    from quest.game import QuestGame
  File "/mnt/c/Users/bryan/desktop/cs9/unit2/quest_lab/quest/game.py", line 1, in <module>
    import arcade
  File "/home/bryan1/.local/lib/python3.6/site-packages/arcade/__init__.py", line 29, in <module>
    from .window_commands import close_window
  File "/home/bryan1/.local/lib/python3.6/site-packages/arcade/window_commands.py", line 10, in <module>
    import pyglet.gl as gl
  File "/home/bryan1/.local/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/home/bryan1/.local/lib/python3.6/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/bryan1/.local/lib/python3.6/site-packages/pyglet/gl/lib_glx.py", line 45, in <module>
    gl_lib = pyglet.lib.load_library('GL')
  File "/home/bryan1/.local/lib/python3.6/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GL" not found.
```

**Comment by cproctor** [comment]
@wolfj95 I did some digging into similar error messages, but it's going to be a bit slow to debug from a distance. Might be fastest to connect me with the person having the error over discord. 

The problem is within pyglet, a lower-level UI library that interfaces with native graphics libraries. Pyglet doesn't note any particular installation issues; should just work. It's possible there is a graphics driver issue, but I would start by 

```
pip uninstall pyglet
pip install pyglet
```

and see if that works.

**Comment by wolfj95** [comment]
I tested with another student using a windows machine after posting this issue and we got the error. Seems to be something with our setup, and I sense your hunch about the graphics processing is correct. We had a potentially related issue working with Turtle graphics. 

I can dig into the installation using a windows machine on Monday and see what I can figure out.

**Comment by cproctor** [comment]
OK, sorry to see this as it's disheartening for code not to work! I'll see if I can get an old windows laptop working to test it too. Are Windows users mostly using WSL?

**Comment by cproctor** [comment]
This is probably a horrible idea, but if there are spare linux machines at ISF, you could run https://guacamole.apache.org/

**Comment by wolfj95** [comment]
Potential solution to the immediate issue is to install freeglut3: `apt install freeglut3-dev`

based on https://stackoverflow.com/questions/50446867/importerror-library-glu-not-found

Another issue persists, but will open a related issue.

**Comment by wolfj95** [comment]
note: after installing freeglut, I also had to install dataclasses: `sudo pip3 install --upgrade dataclasses`

**Comment by wolfj95** [comment]
There is still an error when trying to run an example game from the Quest examples as a module on WSL (ie python3 -m quest.examples.island)

error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/jwolf/Desktop/cs9/unit_02/quest_lab/quest/examples/island.py", line 1, in <module>
    from quest.game import QuestGame
  File "/mnt/c/Users/jwolf/Desktop/cs9/unit_02/quest_lab/quest/game.py", line 1, in <module>
    import arcade
  File "/usr/local/lib/python3.6/dist-packages/arcade/__init__.py", line 226, in <module>
    from .tilemap import get_tilemap_layer
  File "/usr/local/lib/python3.6/dist-packages/arcade/tilemap.py", line 17, in <module>
    import pytiled_parser
  File "/usr/local/lib/python3.6/dist-packages/pytiled_parser/__init__.py", line 3, in <module>
    from . import objects, utilities
  File "/usr/local/lib/python3.6/dist-packages/pytiled_parser/objects.py", line 178, in <module>
    @attr.s(auto_attribs=True, kw_only=True)
TypeError: attrs() got an unexpected keyword argument 'kw_only
```

(Note: after a cascade of errors, moving all WSL error here to keep documentation in a single place)

**Comment by wolfj95** [comment]
pytiled-parser error was corrected by updating attrs: `sudo pip install --upgrade attrs`

**Comment by wolfj95** [comment]
next error is almost certainly related to the graphics discrepancy between WSL and the windows GPU, a much trickier error to resolve:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/jwolf/Desktop/cs9/unit_02/quest_lab/quest/examples/island.py", line 59, in <module>
    game = IslandAdventure()
  File "/mnt/c/Users/jwolf/Desktop/cs9/unit_02/quest_lab/quest/game.py", line 59, in __init__
    super().__init__(self.screen_width, self.screen_height, self.screen_title)
  File "/usr/local/lib/python3.6/dist-packages/arcade/application.py", line 71, in __init__
    resizable=resizable, config=config, vsync=False)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/__init__.py", line 594, in __init__
    context = config.create_context(gl.current_context)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/gl/xlib.py", line 164, in create_context
    return XlibContext10(self, share)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/gl/xlib.py", line 264, in __init__
    super(XlibContext10, self).__init__(config, share)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/gl/xlib.py", line 215, in __init__
    self.glx_context = self._create_glx_context(share)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/gl/xlib.py", line 269, in _create_glx_context
    'Require GLX_ARB_create_context extension to create OpenGL 3 contexts.')
pyglet.gl.ContextException: Require GLX_ARB_create_context extension to create OpenGL 3 contexts.
```

**Comment by wolfj95** [comment]
# Potential resolution
Turns out windows powershell can run pygame modules. Install python3.8 from the windows store and run games from powershell (rather than Ubuntu)

Will test this out with students. Potential for issues to arise installing/using python across WSL and Powershell, but closing for now.
